//
//  ToDoListPresenter.swift
//  ToDoVIP
//
//  Created by Ozan Barış Günaydın on 29.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoListPresentationLogic {
  func presentDatas(response: ToDoList.FetchDatas.Response)
}

class ToDoListPresenter: ToDoListPresentationLogic {
  weak var viewController: ToDoListDisplayLogic?
  
  // MARK: Present Datas
  
  func presentDatas(response: ToDoList.FetchDatas.Response) {
      var displayedDatas: [ToDoList.FetchDatas.ViewModel.DisplayedData] = []
//      let displayedDuties: [ToDoList.FetchDatas.ViewModel.Task] = []
      
      for todo in response.datas {
//          let task = ToDoList.FetchDatas.ViewModel.Task(task: todo.task[0].task)
//          let displayedData = ToDoList.FetchDatas.ViewModel.DisplayedData(day: todo.day, task: [task])
          let displayedData = ToDoList.FetchDatas.ViewModel.DisplayedData(day: todo.day, task: todo.task, completed: todo.completed)
          displayedDatas.append(displayedData)
      }
//      let viewModel = ToDoList.FetchDatas.ViewModel(displayedDatas: displayedDatas, displayedDuties: displayedDuties)
      let viewModel = ToDoList.FetchDatas.ViewModel(displayedDatas: displayedDatas)
      viewController?.displayFetcedDatas(viewModel: viewModel)
  }
}
