//
//  ToDoListWorker.swift
//  ToDoVIP
//
//  Created by Ozan Barış Günaydın on 29.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

final class ToDoListWorker {
    
    func fetchDatas(response: @escaping ([ToDoResponseModel]?) -> Void) {
        guard let url = Bundle.main.url(forResource: "data", withExtension: "json") else { return }
        
        AF.request(url, method: .get).responseDecodable(of: [ToDoResponseModel].self) { (model) in
            guard let data = model.value else {
                print("Error. Failed to fetch data from data.")
                response(nil)
                return
            }
            response(data)
        }
  }
}
