//
//  ToDoListInteractor.swift
//  ToDoVIP
//
//  Created by Ozan Barış Günaydın on 29.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ToDoListBusinessLogic {
  func fetchDatas(request: ToDoList.FetchDatas.Request)
}

protocol ToDoListDataStore {
    var datas: [ToDoResponseModel]? { get }
}

class ToDoListInteractor: ToDoListBusinessLogic, ToDoListDataStore {
    
    var datas: [ToDoResponseModel]?
    
    var presenter: ToDoListPresentationLogic?
    var worker: ToDoListWorker?
    
    // MARK: Fetch Datas
    
    func fetchDatas(request: ToDoList.FetchDatas.Request) {
        worker = ToDoListWorker()
        worker?.fetchDatas(response: { (datas) in
            guard let datas = datas else {
                return
            }
            self.datas = datas
            let response = ToDoList.FetchDatas.Response(datas: datas)
            self.presenter?.presentDatas(response: response)
        })
    }
}
